djangoseis1/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

djangoseis1/boards/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.boards_list)
]

djangoseis1/djangoseis1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lessons/', include('lessons.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about),
    path('markdownx/', include('markdownx.urls')),
    path('martor/', include('martor.urls')),
    path('boards/', include('boards.urls')),
    path('', views.homepage),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

djangoseis1/lessons/urls.py
from django.urls import path
from . import views

app_name = 'lessons'

urlpatterns = [
    path('', views.lessons_list, name="list"),
    path('create/', views.lesson_create, name="create"),
    path('<str:slug>/', views.lesson_detail, name="detail"),
]

djangoseis1/accounts/models.py
from django.db import models

# Create your models here.

djangoseis1/boards/models.py
from django.db import models

# Create your models here.

djangoseis1/lessons/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Lesson(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[:50] +'...'

djangoseis1/lessons/forms.py
from django import forms
from . import models

class CreateLesson(forms.ModelForm): # create own form
    class Meta:
        model = models.Lesson
        fields = ['title', 'body', 'slug', 'thumb']

djangoseis1/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return redirect('lessons:list') # can be changed to homepage
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST: # sent by the GET in login.html
                return redirect(request.POST.get('next'))
            else:
                return redirect('lessons:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form':form })

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('lessons:list')

djangoseis1/boards/views.py
from django.shortcuts import render

# Create your views here.

def boards_list(request):
    return render(request, 'boards/boards_list.html')

djangoseis1/djangoseis1/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request,'homepage.html')
    #return HttpResponse('homepage')

def about(request):
    return render(request,'about.html')
    #return HttpResponse('about')

djangoseis1/lessons/views.py
from django.shortcuts import render, redirect
from .models import Lesson
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def lessons_list(request):
    lessons = Lesson.objects.all().order_by('date')
    return render(request,'lessons/lessons_list.html',{ 'lessons':lessons })

def lesson_detail(request, slug):
    #eturn HttpResponse(slug)
    lesson = Lesson.objects.get(slug=slug)
    return render(request, 'lessons/lessons_detail.html', {'lesson': lesson})

@login_required(login_url="/accounts/login/")
def lesson_create(request):
    if request.method == 'POST':
        form = forms.CreateLesson(request.POST, request.FILES)
        if form.is_valid():
            # save lesson to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('lessons:list')
    else:
        form = forms.CreateLesson()
    return render(request, 'lessons/lessons_create.html', {'form': form})

djangoseis1/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit", value="Login">
    </form>
{% endblock %}

djangoseis1/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit", value="Signup">
    </form>
{% endblock %}

djangoseis1/boards/templates/boards/boards_list.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="boards_list">
    <h2>Boards</h2>
</div>

{% endblock %}

djangoseis1/lessons/templates/lessons/lessons_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="create-article">
    <h2>Create an Awesome Lesson</h2>
    <form class="site-form" action="{% url 'lessons:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
</div>
{% endblock %}

djangoseis1/lessons/templates/lessons/lessons_detail copy.html
{% extends 'base_layout.html' %}
{% load markdownify %}

{% block content %}
<div class="lesson-detail">
    <div class="bodymd">
        <img src="{{ lesson.thumb.url }}"/>
        <h2>{{ lesson.detail }}</h2>
        <p> {{ lesson.body | markdown | safe }}</p>
        <p>{{ lesson.date }}</p>
    </div>
</div>

{% endblock %}

djangoseis1/lessons/templates/lessons/lessons_detail.html
{% extends 'base_layout.html' %}
{% load markdownify %}

{% block content %}
<div class="lesson-detail">
    <div class="bodymd">
        <img src="{{ lesson.thumb.url }}"/>
        <h2>{{ lesson.detail }}</h2>
        <p> {{ lesson.body | markdown | safe }}</p>
        <p>{{ lesson.date }}</p>
    </div>
</div>

{% endblock %}

djangoseis1/lessons/templates/lessons/lessons_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Lessons List</h1>
<div class="lessons">
    {% for lesson in lessons %}
        <div class="lesson">
            <h2><a href="{% url 'lessons:detail' slug=lesson.slug %}">{{ lesson.title }}</a></h2>
            <p> {{ lesson.snippet }}</p>
            <p> {{ lesson.date }}</p>
        </div>
    {% endfor %}
</div>
{% endblock %}

djangoseis1/templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body>
        <h1>About us</h1>
        <p>We love Django</p>
    </body>
</html>

djangoseis1/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Lessons</title>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid" style="width: 1170px; margin: auto;">
                <div class="navbar-header">
                    <a href="#" class="navbar-brand">Belajar Gempabumi</a></h1>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Logout</button>
                        </form>
                    </li>
                    <li>
                        <a href="{% url 'lessons:create' %}">Create</a>
                    </li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-user"></span>Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="jumbotron" style="margin-top: 70px; padding: 80px;">
            <div style="width: 1170px; margin: auto;">
                <h1><a href="{% url 'lessons:list' %}">Lessons</a></h1>
                <p>This is a webpage to learn about how earthquake works!</p>
            </div>
        </div>
        <div class="container" style="margin-top:100px">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

djangoseis1/templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
    </head>
    <body>
        <h1>This is the homepage</h1>
        <p>Welcome to Djangoseis</p>
    </body>
</html>